<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeliveryOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryOrderItemRepository extends EntityRepository
{
}
