<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * InventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends EntityRepository
{
    /**
     * @param Product $product
     * @return array
     */
    public function getProductInventories(Product $product)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.product = ?1')
            ->setParameter(1, $product)
            ->orderBy('i.addedAt', 'ASC')
            ->getQuery();
        var_dump($query->getSQL());
            $query->getResult();
    }

}
